/**
 * PDF Report Generator
 *
 * Generates a structured HTML document that can be converted to PDF
 * via the browser's print functionality or a server-side renderer.
 * For MVP, we generate print-ready HTML; a headless Chrome / Puppeteer
 * pipeline can be added later for true PDF binary output.
 */

import type { GeneratedSection } from "@/types";

interface PDFGeneratorInput {
  title: string;
  frameworkType: string;
  organizationName: string;
  reportingPeriod: string;
  sections: GeneratedSection[];
  generatedAt: Date;
}

/**
 * Generate print-ready HTML for a sustainability report.
 */
export function generateReportHTML(input: PDFGeneratorInput): string {
  const toc = input.sections
    .map(
      (s, i) =>
        `<li><a href="#section-${i}">${s.code} — ${s.title}</a></li>`
    )
    .join("\n");

  const sectionHTML = input.sections
    .map(
      (s, i) => `
      <div class="section" id="section-${i}">
        <h2>${s.code} — ${s.title}</h2>
        <div class="section-content">${markdownToHTML(s.content)}</div>
        ${
          s.dataPointsUsed.length > 0
            ? `<p class="data-points"><strong>Data points covered:</strong> ${s.dataPointsUsed.join(", ")}</p>`
            : ""
        }
      </div>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHTML(input.title)}</title>
  <style>
    @media print {
      body { font-size: 11pt; }
      .page-break { page-break-before: always; }
      .no-print { display: none; }
    }
    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      line-height: 1.6;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #1a1a1a;
    }
    .cover {
      text-align: center;
      padding: 80px 0;
      border-bottom: 2px solid #059669;
      margin-bottom: 40px;
    }
    .cover h1 {
      font-size: 28pt;
      color: #059669;
      margin-bottom: 8px;
    }
    .cover .org-name {
      font-size: 18pt;
      color: #374151;
      margin-bottom: 4px;
    }
    .cover .meta {
      font-size: 11pt;
      color: #6b7280;
    }
    .toc {
      margin: 40px 0;
      padding: 20px;
      background: #f9fafb;
      border-radius: 8px;
    }
    .toc h2 { font-size: 14pt; margin-bottom: 12px; }
    .toc ol { padding-left: 20px; }
    .toc li { margin-bottom: 4px; }
    .toc a { color: #059669; text-decoration: none; }
    .section {
      margin-bottom: 32px;
      padding-bottom: 24px;
      border-bottom: 1px solid #e5e7eb;
    }
    .section h2 {
      color: #059669;
      font-size: 16pt;
      margin-bottom: 12px;
    }
    .section h3 {
      font-size: 13pt;
      color: #374151;
      margin-top: 16px;
    }
    .section-content p { margin-bottom: 8px; }
    .data-points {
      font-size: 9pt;
      color: #9ca3af;
      margin-top: 16px;
      padding-top: 8px;
      border-top: 1px dashed #e5e7eb;
    }
    .footer {
      text-align: center;
      font-size: 9pt;
      color: #9ca3af;
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
    }
  </style>
</head>
<body>
  <div class="cover">
    <h1>${escapeHTML(input.title)}</h1>
    <p class="org-name">${escapeHTML(input.organizationName)}</p>
    <p class="meta">${escapeHTML(input.frameworkType)} Report — ${escapeHTML(input.reportingPeriod)}</p>
    <p class="meta">Generated ${input.generatedAt.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>
  </div>

  <div class="toc">
    <h2>Table of Contents</h2>
    <ol>${toc}</ol>
  </div>

  <div class="page-break"></div>

  ${sectionHTML}

  <div class="footer">
    <p>This report was generated by GreenLedger. Sections marked as AI-generated should be reviewed by qualified personnel before submission.</p>
    <p>Generated on ${input.generatedAt.toISOString()}</p>
  </div>
</body>
</html>`;
}

/**
 * Generate CSV export of report data points.
 */
export function generateReportCSV(
  sections: GeneratedSection[]
): string {
  const rows = [
    ["Section Code", "Section Title", "Confidence", "Data Points Covered"].join(
      ","
    ),
  ];

  for (const s of sections) {
    rows.push(
      [
        csvEscape(s.code),
        csvEscape(s.title),
        String(s.confidence),
        csvEscape(s.dataPointsUsed.join("; ")),
      ].join(",")
    );
  }

  return rows.join("\n");
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function csvEscape(str: string): string {
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

/**
 * Basic markdown to HTML conversion for report content.
 * Handles headings, paragraphs, bold, italic, lists, and line breaks.
 */
function markdownToHTML(md: string): string {
  return md
    .split("\n\n")
    .map((block) => {
      const trimmed = block.trim();
      if (!trimmed) return "";

      // Headings
      if (trimmed.startsWith("### "))
        return `<h4>${trimmed.slice(4)}</h4>`;
      if (trimmed.startsWith("## "))
        return `<h3>${trimmed.slice(3)}</h3>`;
      if (trimmed.startsWith("# "))
        return `<h2>${trimmed.slice(2)}</h2>`;

      // Bullet lists
      if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        const items = trimmed
          .split("\n")
          .filter((l) => l.startsWith("- ") || l.startsWith("* "))
          .map((l) => `<li>${inlineMarkdown(l.slice(2))}</li>`)
          .join("");
        return `<ul>${items}</ul>`;
      }

      // Numbered lists
      if (/^\d+\.\s/.test(trimmed)) {
        const items = trimmed
          .split("\n")
          .filter((l) => /^\d+\.\s/.test(l))
          .map((l) => `<li>${inlineMarkdown(l.replace(/^\d+\.\s/, ""))}</li>`)
          .join("");
        return `<ol>${items}</ol>`;
      }

      return `<p>${inlineMarkdown(trimmed)}</p>`;
    })
    .join("\n");
}

function inlineMarkdown(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/`(.+?)`/g, "<code>$1</code>");
}
